Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
  
    config.vm.define "EkaymazS" do |server|
      server.vm.hostname = "EkaymazS"
      server.vm.network "private_network", ip: "192.168.56.110"
  
      server.vm.provider "virtualbox" do |vb|
        vb.name = "EkaymazS"
        vb.memory = 1024
        vb.cpus = 1
      end
  
      server.vm.synced_folder "./scripts", "/vagrant/scripts"
      server.vm.synced_folder "./confs", "/vagrant/confs"
      server.vm.provision "shell", path: "./scripts/install_server.sh"
    end
  end
  